# DB RELATED CONSTATNTS
#----------------------------------------#
DATA_BASE_NAME="gitfit-tracker"
MONGODB_URL_GITFIT="MONGO_GITFIT_URL"


# pose related constant
MIN_DETECTION_CONFIDENCE=0.6
MIN_TRACKING_CONFIDECNE=0.6

"""WARM UP RELATED CONSTANTS"""
# HEAD ROLL WARMUP
SIDE_HIGH_THRESHOLD_HEADROLL=1
SIDE_LOW_THRESHOLD_HEADROLL=0.8
HEAD_FORWARD_THRESHOLD_HEADROLL=0.8
HEAD_BACK_THRESHOLD_HEADROLL=0.9

# JUMPING JACK WARMUP
HIGH_THRESHOLD_JUMPING_JACK=170
LOW_THRESHOLD_JUMPING_JACK=90

# LEG SWING WARMUP
HIGH_THRESHOLD_LEG_SWING=172
LOW_THRESHOLD_LEG_SWING=160

# LEG SIDE SWING WARMUP
HIGH_THRESHOLD_LEG_SIDE_SWING=172
LOW_THRESHOLD_LEG_SIDE_SWING=135

# WARMUP INITIATION CONTANTS
MIN_COUNTER_TO_SWITCH_WARMUP=10
MIN_TIME_TO_SWITCH_WARMUP=45

#  BOX SQUART CONSTANTS
HIP_LOW_THRESHOLD_BOX_SQUART=140
HIP_HIGH_THRESHOLD_BOX_SQUART=175
KNEE_LOW_THRESHOLD_BOX_SQUART=120
KNEE_HIGH_THRESHOLD_BOX_SQUART=175

# PUSH UP RELATED CONSTANT
ELBOW_HIGH_THRESHOLD_PUSH_UP=175
ELBOW_LOW_THRESHOLD_PUSH_UP=60

# PUSH UP RELATED CONSTANT
ELBOW_HIGH_THRESHOLD_TRICEP_PUSH_UP=175
ELBOW_LOW_THRESHOLD_TRICEP_PUSH_UP=90

# SHOULDER TAP RELATED CONSTANT
ELBOW_ANGLE_THRESHOLD_SHOULDER_TAP=175
WRIST_SHOULDER_DISTANCE_SHOULDER_TAP=0.7

# CRUNCHESE REALTED CONSTANT
HIP_HIGH_THRESHOLD_CRUNCHES=150
HIP_LOW_THRESHOLD_CRUNCHES=100
